import React from 'react'
import Head from 'next/head'
import Homepage from '@/components/Homepage'
import Footer from '@/components/Footer'


const index = () => {
    return (
        <>
            <Head>
                <title>Home</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <Homepage />
            <Footer />
        </>
    )
}

export default index