import Head from 'next/head';
import styles from '@/styles/Login.module.css';
import React, { useState, useEffect } from 'react';
import { Avatar, Button, TextField, Typography, Link } from '@mui/material';
import { Lock } from '@mui/icons-material';
import { blue } from '@mui/material/colors';
import Cookies from 'js-cookie';
import CryptoJS from 'crypto-js';

interface Vendor {
  email: string;
  password: string;
}

function encryptFunction(data: string): any {
  return CryptoJS.AES.encrypt(data, "key");
}

function LoginPage(): JSX.Element {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [vendorsData, setVendorsData] = useState<Vendor[]>([]);

  useEffect(() => {
    fetch('../../vendors.json')
      .then((response) => response.json())
      .then((data) => setVendorsData(data))
      .catch((error) => console.error('Error fetching vendors:', error));
  }, []);

  const handleEmailChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setEmail(e.target.value);
  };

  const handlePasswordChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setPassword(e.target.value);
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    console.log('Email:', email);
    console.log('Password:', password);
    const matchedVendor = vendorsData.find(
      (vendor) => vendor.email === email && vendor.password === password
    );

    if (matchedVendor) {
      console.log('Login successful!');
      const encryptedData = encryptFunction(JSON.stringify({ email, password }));
      Cookies.set('userData', encryptedData, { expires: 1 });
      window.location.href = '/backend';
    } else {
      console.log('Login failed. Invalid email or password.');
    }
    setEmail('');
    setPassword('');
  };

  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <Avatar sx={{ bgcolor: blue[500] }}>
            <Lock />
          </Avatar>
          <h1>Log in to your account</h1>
          <form onSubmit={handleSubmit}>
            <TextField
              margin="normal"
              required
              fullWidth
              id="email"
              label="Email Address"
              name="email"
              autoComplete="email"
              autoFocus
              type="text"
              value={email}
              onChange={handleEmailChange}
            />
            <TextField
              margin="normal"
              required
              fullWidth
              name="password"
              label="Password"
              type="password"
              id="password"
              autoComplete="current-password"
              value={password}
              onChange={handlePasswordChange}
            />
            <Button className={styles.btn} fullWidth type="submit" variant="contained">
              Log in
            </Button>
          </form>
          <Typography variant="body2" color="text.secondary" align="center" sx={{ mt: 8, mb: 4 }}>
            {'Copyright © '}
            <Link color="inherit" href="/frontend">
              Cyberclothing
            </Link>{' '}
            {new Date().getFullYear()}
            {'.'}
          </Typography>
        </div>
      </main>
    </>
  );
}

export default LoginPage;
