import Head from 'next/head'
import styles from '@/styles/Login.module.css'
import React, { useState } from 'react'
import { Avatar, Button, TextField, Typography, Link } from '@mui/material'
import { Lock } from '@mui/icons-material'
import { blue } from '@mui/material/colors'

function Copyright(props: any) {
  return (
    <Typography variant="body2" color="text.secondary" align="center" {...props}>
      {'Copyright © '}
      <Link color="inherit" href="#">
        Your Website
      </Link>{' '}
      {new Date().getFullYear()}
      {'.'}
    </Typography>
  );
}


const LoginPage = () => {
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')

  const handleEmailChange = (e: any) => {
    setEmail(e.target.value)
  }

  const handlePasswordChange = (e: any) => {
    setPassword(e.target.value);
  }

  const handleSubmit = (e: any) => {
    e.preventDefault();
    console.log('Email:', email);
    console.log('Password:', password);
    setEmail('');
    setPassword('');
  };


  // Task 1: Create Login Screen Victor
  //  https://pro.chakra-ui.com/components/application/authentication
  //  Use MUI Input elemnts https://mui.com/material-ui/react-table/

  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="Lock" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <Avatar sx={{ bgcolor: blue[500] }}>
            <Lock />
          </Avatar>
          <h1>Log in to your account</h1>
          <form onSubmit={handleSubmit}>
            <TextField
              margin="normal"
              required
              fullWidth
              id="email"
              label="Email Address"
              name="email"
              autoComplete="email"
              autoFocus
              type="text" value={email}
              onChange={handleEmailChange}
            />
            <TextField
              margin="normal"
              required
              fullWidth
              name="password"
              label="Password"
              type="password"
              id="password"
              autoComplete="current-password"
              value={password}
              onChange={handlePasswordChange}
            />
            <Button className={styles.btn} fullWidth type="submit" variant='contained'>Log in</Button>
          </form>
          <Copyright sx={{ mt: 8, mb: 4 }} />
        </div>
      </main>
    </>
  )
}
export default LoginPage
