import React from 'react'
import Head from 'next/head'
import Cart from '@/components/Cart'

const index = () => {
    return (
        <>
            <Head>
                <title>Cart</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <Cart />
        </>
    )
}

export default index